### ISSUE TITLE
width的propTypes类型错误

### ISSUE THREAD

**Issue by 4tj** [tinglejs/tingle-tip#8]
<img width="627" alt="2015-09-30 1 29 31" src="https://cloud.githubusercontent.com/assets/1736244/10185138/50a97d22-6777-11e5-8813-c07363d672dc.png">
https://github.com/tinglejs/tingle-tip/blob/master/src/Tip.js#L87

此处类型应为number

**Comment by yize** [comment]
Fixed in #9
